### ISSUE TITLE
温度跟踪的时候能不能再框后面显示温度数值

### ISSUE THREAD

**Issue by wangfreexx** [colourfate/ThermalEyes#2]
![image](https://github.com/colourfate/ThermalEyes/assets/23137882/37ac6036-6bba-4eea-a75c-021ad86d9f56)
类似这样

**Comment by colourfate** [comment]
之前尝试做了一下，感觉框和数字到处乱跳，看着不太方便

**Comment by wangfreexx** [comment]
感谢解答，还有就是当摄像头和热成像没对齐（垂直，水平都有一定偏差）的情况下，提供的对齐参数有点少，不知道能不能更多的对齐参数

**Comment by colourfate** [comment]
是使用了3d打印外壳垂直、水平都有偏差吗？因为对齐会对图像进行裁剪和扩充，会影响图像效果，不建议进行太多的对齐

**Comment by wangfreexx** [comment]
没有用外壳，后续用外壳试试
